pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Run Unit Tests') {
            steps {
                sh 'pytest tests/'
            }
        }

        stage('Evaluate Model') {
            steps {
                sh 'python model/evaluate_model.py'
            }
        }

        stage('Deploy Model') {
            steps {
                sh 'cp model/model.pkl deployed_model/model.pkl'
            }
        }
    }
}
